name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Verify repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4

      - name: Setup Ruby
        uses: ruby/setup-ruby@d7b76f909a9ce4f0102c606459aa23439865bd38 # 1.50.0
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Run tests
        run: rake test
